const BREEDS_MAP: Record<string, string> = {
  // Perros
  afghan_hound: "Afghan Hound",
  akita: "Akita",
  alaskan_malamute: "Alaskan Malamute",
  basset_hound: "Basset Hound",
  beagle: "Beagle",
  bichon_frise: "Bichón Frisé",
  border_collie: "Border Collie",
  boxer: "Boxer",
  bulldog: "Bulldog",
  french_bulldog: "Bulldog Francés",
  bull_terrier: "Bull Terrier",
  chihuahua: "Chihuahua",
  chow_chow: "Chow Chow",
  cocker_americano: "Cocker Americano",
  cocker_spaniel: "Cocker Spaniel",
  collie: "Collie",
  corgi: "Corgi",
  dachshund: "Dachshund (Salchicha)",
  dalmata: "Dálmata",
  doberman: "Doberman",
  galgo: "Galgo",
  golden_retriever: "Golden Retriever",
  husky: "Husky Siberiano",
  labrador: "Labrador Retriever",
  maltese: "Maltés",
  mixed: "Mestizo",
  pastor_aleman: "Pastor Alemán",
  pitbull: "Pitbull",
  pomeranian: "Pomerania",
  poodle: "Poodle",
  pug: "Pug",
  rottweiler: "Rottweiler",
  samoyedo: "Samoyedo",
  san_bernardo: "San Bernardo",
  schnauzer: "Schnauzer",
  shar_pei: "Shar Pei",
  shih_tzu: "Shih Tzu",
  terranova: "Terranova",
  west_highland: "West Highland White Terrier",
  yorkshire: "Yorkshire Terrier",
  // Gatos
  abyssinian: "Abisinio",
  bengal: "Bengalí",
  birman: "Birmano",
  british_shorthair: "British Shorthair",
  burmese: "Burmés",
  exotic_shorthair: "Exotic Shorthair",
  maine_coon: "Maine Coon",
  norwegian_forest: "Noruego de Bosque",
  persian: "Persa",
  ragdoll: "Ragdoll",
  russian_blue: "Azul Ruso",
  scottish_fold: "Scottish Fold",
  siamese: "Siamés",
  sphynx: "Sphynx (Sin Pelo)",
  american_shorthair: "American Shorthair",
  munchkin: "Munchkin",
  oriental: "Oriental",
};

export const translateBreed = (breedId: string): string => {
  return BREEDS_MAP[breedId] || breedId; // Devuelve el nombre o el ID si no lo encuentra
};
